### ISSUE TITLE
Automate offline Conda repositories

### ISSUE THREAD

**Issue by debrando** [prometeia/continuous-integration#1]
Al momento abbiamo un solo caso, halkbank, ma potrebbe estendersi e comunque è oneroso. Trovare una procedure più  pulita della attuale e/o automatizzarla quanto possibile.

**Comment by glaucouri** [comment]
Mi risulta che tutte le installazioni di RatingPro abbiano questa "caratteristica":
AlexBank (egitto)  RP 3.0
TSKB (turchia) RP 3.2
Muletto di presentazione RP 3.0 ?
Koperbanca (capo d'istria ) RP 3.0
piu probabilmente un altro paio che non conosco ;-)

**Comment by debrando** [comment]
Il prototipo in contesto Windows sembra funzionare, triangolando da G:\PYTHO-offline-repo. Anche il comportamento di _robocopy_ è come da aspettative.

In installazione, nel test sulla mia macchina escono i seguenti errori, che direi imputabili a conflitti locali nei link dei pacchetti: bisognerebbe provare su una macchina terza:

    SafetyError: The package for spyne located at C:\Users\brandolinid\AppData\Local\Continuum\miniconda2\pkgs\spyne-2.12.14-py27h0177efa_0
    appears to be corrupted. The path 'Scripts/sort_wsdl-script.py'
    has a sha256 mismatch.
    reported sha256: e03207e4cc8b656cb28682074cd401f7ad8c6df157012768aae535a9adc6425a
    actual sha256: cc71464c9fc7fe67b4816f8f045d40ef585173d3bf611ef4cee4fe62e22dc3f2

    ClobberError: This transaction has incompatible packages due to a shared path.
    packages: file:///c:/tmp/halkbankofflinerepo::setuptools-38.5.1-py27_0, file:///c:/tmp/halkbankofflinerepo::voluptuous-0.8.11-py27_0
    path: 'scripts/easy_install-2.7-script.py'

    ClobberError: This transaction has incompatible packages due to a shared path.
    packages: file:///c:/tmp/halkbankofflinerepo::setuptools-38.5.1-py27_0, file:///c:/tmp/halkbankofflinerepo::voluptuous-0.8.11-py27_0
    path: 'scripts/easy_install-2.7.exe'

Procedo a individuare i riferimenti delle installazioni offline cui sopra, preparare i pacchetti, e fare se possibile i test in quel contesto (i.e. non sulle produzioni).

**Comment by debrando** [comment]
Ufficialmente abbiamo in manutenzione le seguenti versioni:
- 4.1, rilasciata
- 4.2, in alfa

**Comment by debrando** [comment]
Ho ridefinito il processo secondo le nuove pipeline standard, master su pythociw e slave su linux. La nuova procedura, anziché fare hacking della cache, dopo aver installato i pacchetti target (es. pytho==4.2 gsf==4.1.2) procede a chiedere l'elenco esteso completo dei pacchetti presenti nell'ambiente, incluse dunque le dipendenze. Procede quindi a scaricare gli stessi dall'url fornito (di solito, anaconda), per poi indicizzare e metterli sulla sharedfolder: processo lento, ma massimamente sicuro.

La [pipeline offconda](http://pythociw:8080/blue/organizations/jenkins/offconda/branches) prende come parametri:
- il "colore" della soluzione, ovvero il macro-nome del pacchetto di rilascio alla tal versione, default "PYTHO_0402";
- i pacchetti target da installarsi,  defautlt "pytho==4.2 gsf_datamanagement==4.1.2 gsf==4.1.2".

Attualmente è da azionarsi e configurarsi a mano; trasportato su jenkins anche le altre build, si potrebbe automatizzare il lancio sui rilasci (tag su master dei relativi progetti).

Il risultato finisce sotto la sharedfolder _\\Pythociw\condaoffline_, con sottocartella pari al colore: a default ora quindi *\\Pythociw\condaoffline\PYTHO_0402*

Non essendo a dominio solito la macchina Pythociw, ho creato un utente sola lettura per leggere la shared folder, nome "pythooffline", passowrd sul solito documento [Account e Credenziali](https://docs.google.com/document/d/1WbF4TUOTr_geREnWivpU-RyEceq6Vp1jpE79oHPMiW4)

**Comment by debrando** [comment]
Test di installazione pytho alla versione ultima presente nel canale:

    conda install -c \\Pythociw\condaoffline\PYTHO_0402 --offline --override-channels pytho

A delivery si potrebbe dare l'account cui sopra o uno dedicato, oppure fargli una copia dove gli venga più comodo. Sarei per la prima, così che possano loro in autonomia trasferire le cose dove consono.

*NOTA* Si potrebbe valutare di esporre direttamente il canale con un web server, e più in generale di puntare tutte le installazioni a questi canali autogestiti, anziché a conda; ci vorrebbe però una macchina adeguata alla visibilità dall'esterno, non pythociw.
