### ISSUE TITLE
Automate doc packaging

### ISSUE THREAD

**Issue by debrando** [prometeia/continuous-integration#3]
Create a single one-click procedure to extract, create, tag, upload and label a new doc revision.

Ref: job [pytho_docs_package](https://travis-ci.com/prometeia/pytho_docs_package)

**Comment by glaucouri** [comment]
we must guarantee that the package is done also in offline and we must make sure that it will be a requirement for pytho and ratingpro

**Comment by debrando** [comment]
Same work for: prometeia/pytho-front#2

**Comment by debrando** [comment]
Viste le evoluzioni e sinergie, ho optato per triangolare da un repository dedicato.

@loredanaribatto, la documentazione HTML è ora direttamente inserita nel progetto [prometeia/pytho_docs](https://github.com/prometeia/pytho_docs) e impacchettata come App standard Django da una [pipeline standard](http://pythociw:8080/blue/organizations/jenkins/pytho_docs/branches).

La procedura di sviluppo della stessa è dunque identica a quella dei sorgenti, tramite checkout git locale, salvataggio sullo stesso delle pagine modificate prese da Mezzanine (massivo o puntuale), seguito da commit e push.

Quando passeremo alla nuova documentazione, analogamente su modifiche si farà export dallo strumento e salvataggio in locale su git. Eventualmente potremo valutare poi di automatizzare il processo, azionando su commit nel repository che avrà i sorgenti effettivi.

Attualmente su [develop](https://github.com/prometeia/pytho_docs/tree/develop) ho riportato la docuentazione ultima pubblicata 4.2.1, con bump versione alla 4.3.0
